server:
  port: 8020

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8020/eureka/
  server:
    eviction-interval-timer-in-ms: 60
    enable-self-preservation: true


spring:
  application:
    name: eureka
